import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../models/room.dart';
import '../services/app_services.dart';
import 'room_detail.dart';
import 'map_search.dart';
import 'chat.dart';

class CustomerHome extends StatefulWidget{final bool needsRole;const CustomerHome({super.key,this.needsRole=false});State<CustomerHome> createState()=>_CustomerState();}
class _CustomerState extends State<CustomerHome>{int tab=0;String city='';int? max;final maxCtl=TextEditingController();
Future<void> role(String r)async=>db.collection('users').doc(auth.currentUser!.uid).set({'role':r,'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));
Widget card(Room r){return Card(clipBehavior:Clip.antiAlias,child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RoomDetail(room:r))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(r.photos.isNotEmpty)Image.network(r.photos.first,height:190,width:double.infinity,fit:BoxFit.cover),Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r.title,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18))),if(r.verified)const Icon(Icons.verified,size:18)]),Text('${r.area}, ${r.city}'),const SizedBox(height:8),Text('Rs. ${r.rent}/month',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Wrap(spacing:6,children:[if(r.furnished)const Chip(label:Text('Furnished')),if(r.wifi)const Chip(label:Text('Wi‑Fi')),if(r.parking)const Chip(label:Text('Parking'))])]))]));}
Widget home(){return StreamBuilder<List<Room>>(stream:RoomService().rooms(city:city,maxRent:max),builder:(c,s){final rs=s.data??[];return CustomScrollView(slivers:[SliverAppBar(pinned:true,title:const Text('Find your next room'),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MapSearch())),icon:const Icon(Icons.map_outlined))]),SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,16,16,4),child:Row(children:[Expanded(child:DropdownButtonFormField<String>(value:city.isEmpty?null:city,decoration:const InputDecoration(labelText:'City'),items:['Kathmandu','Lalitpur','Bhaktapur','Pokhara'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>city=v??''))),const SizedBox(width:10),SizedBox(width:130,child:TextField(controller:maxCtl,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Max rent'),onSubmitted:(v)=>setState(()=>max=int.tryParse(v))) )]))),if(s.connectionState==ConnectionState.waiting)const SliverFillRemaining(child:Center(child:CircularProgressIndicator())) else if(rs.isEmpty)const SliverFillRemaining(child:Center(child:Text('No approved rooms found. Try another filter.'))) else SliverPadding(padding:const EdgeInsets.all(16),sliver:SliverList.builder(itemCount:rs.length,itemBuilder:(c,i)=>Padding(padding:const EdgeInsets.only(bottom:12),child:card(rs[i]))))]);}
Widget build(BuildContext c){if(widget.needsRole)return Scaffold(body:Center(child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('How will you use KothaFinder?',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:18),FilledButton.icon(onPressed:()=>role('customer'),icon:const Icon(Icons.search),label:const Text('I am looking for a room')),OutlinedButton.icon(onPressed:()=>role('landlord'),icon:const Icon(Icons.home_work),label:const Text('I want to list a room'))]))));return Scaffold(body:[home(),const FavoritesPage(),const MessagesPage()][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.search),label:'Find'),NavigationDestination(icon:Icon(Icons.favorite_border),label:'Saved'),NavigationDestination(icon:Icon(Icons.chat_bubble_outline),label:'Messages')]));}
}
class FavoritesPage extends StatelessWidget{const FavoritesPage({super.key});Widget build(BuildContext c)=>StreamBuilder<List<String>>(stream:FavoriteService().ids(),builder:(c,s)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('rooms').where(FieldPath.documentId,whereIn:(s.data??const []).isEmpty?['__none__']:(s.data??const [])).snapshots(),builder:(c,r)=>ListView(children:[const ListTile(title:Text('Saved rooms',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),...((r.data?.docs??[]).map((d)=>ListTile(title:Text(d.data()['title']??''),subtitle:Text('Rs. ${d.data()['rent']??0}/month'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RoomDetail(room:Room.fromDoc(d))))))]))));}
class MessagesPage extends StatelessWidget{const MessagesPage({super.key});Widget build(BuildContext c)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:db.collection('conversations').where('participants',arrayContains:auth.currentUser!.uid).orderBy('updatedAt',descending:true).snapshots(),builder:(c,s)=>ListView(children:[const ListTile(title:Text('Messages',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold))),...((s.data?.docs??[]).map((d)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(d.data()['lastMessage']??'Conversation'),subtitle:Text('Tap to continue'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatPage(conversationId:d.id,roomId:d.data()['roomId']??'',receiverId:(d.data()['participants'] as List).firstWhere((x)=>x!=auth.currentUser!.uid)))))))]));}
